### PR TITLE
Fix git error introduced in git 2.35.2

### PR DESCRIPTION
**Pull request by nathanbrock**
Git v2.35.2 spec changes are causing this action to error during run.

Related issues;

- https://github.com/reviewdog/action-misspell/issues/43
- https://github.com/reviewdog/action-misspell/issues/42
- https://github.com/reviewdog/reviewdog/issues/1158#issue-1202862728
- https://github.com/reviewdog/action-yamllint/issues/18

This PR follows the same process to fix the issue as the PR fix in action-yamllint.

### CODE REVIEW

**Comment by shogo82148** [comment]
ref. https://git-scm.com/docs/git-config/2.35.2#Documentation/git-config.txt-safedirectory

> safe.directory
> 
> These config entries specify Git-tracked directories that are considered safe even if they are owned by someone other than the current user. By default, Git will refuse to even parse a Git config of a repository owned by someone else, let alone run its hooks, and this config setting allows users to specify exceptions, e.g. for intentionally shared repositories (see the --shared option in [git-init[1]](https://git-scm.com/docs/git-init)).
> 
> This is a multi-valued setting, i.e. you can add more than one directory via git config --add. To reset the list of safe directories (e.g. to override any such directories specified in the system config), add a safe.directory entry with an empty value.
> 
> This config setting is only respected when specified in a system or global config, not when it is specified in a repository config or via the command line option -c safe.directory=<path>.
> 
> The value of this setting is interpolated, i.e. ~/<path> expands to a path relative to the home directory and %(prefix)/<path> expands to a path relative to Git’s (runtime) prefix.

**Review by shogo82148 — APPROVED** [review]
LGTM!

**Comment by review-dog** [comment]
Hi, @nathanbrock! We merged your PR to reviewdog! 🐶
Thank you for your contribution! ✨

**We just invited you to join the @reviewdog organization on GitHub.**
Accept the invite by visiting https://github.com/orgs/reviewdog/invitation.
By joining the team, you'll be a part of reviewdog community and can help the maintenance of reviewdog.

Thanks again!

**Comment by review-dog** [comment]
Hi, @nathanbrock! We merged your PR to reviewdog! 🐶
Thank you for your contribution! ✨

**We just invited you to join the @reviewdog organization on GitHub.**
Accept the invite by visiting https://github.com/orgs/reviewdog/invitation.
By joining the team, you'll be a part of reviewdog community and can help the maintenance of reviewdog.

Thanks again!

**Comment by shogo82148** [comment]
hmm, It looks that haya14busa/action-bumpr@v1 has same issue

https://github.com/reviewdog/action-languagetool/runs/6006226121?check_suite_focus=true

```
"bump:patch"
Bump patch version
fatal: unsafe repository ('/github/workspace' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
/entrypoint.sh: line 116: : Permission denied
failed to run `git tag`: exit status 128
failed to run `git tag`: exit status 128
fatal: unsafe repository ('/github/workspace' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
fatal: not in a git directory
```

**Comment by nathanbrock** [comment]
Bumpr has been updated 🎉  Would it be ok to re-run the release action, @shogo82148 ?

**Pull request merged**
